Found couple of things helpful for README
ringcentral/ringcentral-java pull request #28
Opened 2021-07-01 04:35 UTC by suyashjoshi

Added a few things that will help new java developers finding key information to quickly get started using our Java SDK.

2021-07-15 00:12 UTC, tylerlong requested changes
Could you please make some minor changes? 
> This SDK is tested against [JDK 11](https://adoptopenjdk.net) so we recommend using the same.
Add "earlier versions such as Java 8 should work as well, please report issues if you encounter any"

Change

> You can find the latest versions in the [project's release page.](https://github.com/ringcentral/ringcentral-java/releases)

to "You can find the latest versions in [Maven Central](https://search.maven.org/search?q=a:ringcentral)".

Thanks

2021-07-30 23:13 UTC, suyashjoshi commented
Made the new changes

2021-09-29 17:47 UTC, tylerlong approved these changes

2021-09-29 17:47 UTC, closed without merging

2021-09-29 17:50 UTC, tylerlong commented
I didn't find the merge button so I manually made the change.

Thank you very much for the PR!